### ISSUE TITLE
Enhancement: Publishing on pypi

### ISSUE THREAD

**Issue by foxriver76** [scikit-multiflow/scikit-multiflow#83]
Is there any reason to not publish the package on [pypi](https://pypi.org/)?
This would allow the users having a more friendly install and upgrade routine and ensures the package name will not be taken by someone else on pypi.

**Comment by jacobmontiel** [comment]
Thanks for the info @jklaise 

We will have updates soon on this topic.

**Comment by jacobmontiel** [comment]
The initial release is available in PyPI: https://pypi.org/project/scikit-multiflow/

I performed some tests locally but would be great if somebody can confirm that the installation works.

```shell
pip install scikit-multiflow
```

**Comment by hmgomes** [comment]
> The initial release is available in PyPI: https://pypi.org/project/scikit-multiflow/
> 
> I performed some tests locally but would be great if somebody can confirm that the installation works.
> 
> ```shell
> pip install scikit-multiflow
> ```

Hi @jacobmontiel 

It failed here:  

_[...]
In file included from src/skmultiflow/lazy/src/libNearestNeighbors/nearestNeighbor.cpp:2:
    In file included from /anaconda3/envs/py3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /anaconda3/envs/py3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /anaconda3/envs/py3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:
    /anaconda3/envs/py3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    src/skmultiflow/lazy/src/libNearestNeighbors/nearestNeighbor.cpp:3:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1_

Best Regards, 
Heitor

**Comment by jacobmontiel** [comment]
Thanks for testing this @hmgomes 

My first idea is that some development tools are missing in your system, are you using MacOS? I found something similar here https://github.com/stan-dev/pystan/issues/470

Note: I tried installing in an anaconda environment under Ubuntu and via Google Colab and did not get errors.

**Comment by jklaise** [comment]
@jacobmontiel thanks for this! Tested installation works on Linux in a Python 3.7 conda environment.

@hmogmes is pip pulling in the .whl file or the source code? If it's pulling in the source code (can happen when your Python environment or OS doesn't support wheel installation) it would build the C++ extension from source which means you need the right gcc/g++ compiler installed.

**Comment by hmgomes** [comment]
I was trying to install it in a conda environment :) 
It worked in my main python 3.7 environment. 

Thanks!

**Comment by garawalid** [comment]
@jacobmontiel 
It works on Linux for both python 3.5 and python 3.6.
Thanks !

**Comment by jacobmontiel** [comment]
@hmgomes Some people are reporting the same issue when installing on OSX + Anaconda via pip.

Can you try the following in a conda environment?

```
$ conda install llvm gcc libgcc
$ pip install -U scikit-multiflow
```

It is strange since other users have no issues on similar setups.

**Comment by hmgomes** [comment]
> @hmgomes Some people are reporting the same issue when installing on OSX + Anaconda via pip.
> 
> Can you try the following in a conda environment?
> 
> ```
> $ conda install llvm gcc libgcc
> $ pip install -U scikit-multiflow
> ```
> It is strange since other users have no issues on similar setups.

@jacobmontiel unfortunately, it didn't work. I got the same error as before. Did it work with other users? I am using OS Mojave (10.14.2), details about the conda environment: 

```
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
```

Best Regards, 

Heitor

**Comment by jacobmontiel** [comment]
I am closing this since the problem mentioned above seems related to anaconda. If needed we can open a new issue for it.
